version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: biblioteca-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=minhaSenha123
      - POSTGRES_DB=BibliotecaDigital
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-api
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=BibliotecaDigital;Username=postgres;Password=minhaSenha123
    networks:
      - app-network

volumes:
  postgres-data:
    name: biblioteca-postgres-data

networks:
  app-network:
    driver: bridge
    name: app-network
